name: Tests

on:
  workflow_run:
    workflows: [Upload data]
    types:
      - completed
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: 16

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    needs: [ eslint ]

    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

  unit:
    name: Unitários
    runs-on: ubuntu-latest
    needs: [ setup ]

    steps:
      - name: Code Linting
        run: echo "Teste unitários"

  spec:
    name: Especificação
    runs-on: ubuntu-latest
    needs: [ setup ]

    steps:
      - name: Code Linting
        run: echo "Teste especificação"
